// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as Theme from "../../styles/Theme.js";
import * as React from "react";

var wrapperBefore = CssJs.before([
      CssJs.position("absolute"),
      CssJs.top({
            NAME: "rem",
            VAL: -1
          }),
      CssJs.left("zero"),
      CssJs.display("inlineBlock"),
      CssJs.width({
            NAME: "rem",
            VAL: 3.5
          }),
      CssJs.borderTop({
            NAME: "px",
            VAL: 6
          }, "solid", Theme.Colors.primary),
      CssJs.unsafe("content", "\"\"")
    ]);

var wrapper = CssJs.style([
      CssJs.marginTop(Theme.Spacing.large),
      CssJs.fontSize(Theme.Font.Sizes.xxlarge),
      CssJs.fontWeight("bold"),
      CssJs.position("relative"),
      wrapperBefore
    ]);

var Styles = {
  wrapper: wrapper
};

function Separator(Props) {
  var children = Props.children;
  return React.createElement("h2", {
              className: wrapper
            }, children);
}

var make = Separator;

export {
  Styles ,
  make ,
  
}
/* wrapperBefore Not a pure module */
