// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";

function add(param) {
  CssJs.$$global("*", [
        CssJs.boxSizing("borderBox"),
        CssJs.padding("zero"),
        CssJs.margin("zero")
      ]);
  CssJs.$$global("html,body", [
        CssJs.height({
              NAME: "percent",
              VAL: 100.0
            }),
        CssJs.width({
              NAME: "percent",
              VAL: 100.0
            })
      ]);
  return CssJs.$$global("body", [CssJs.backgroundColor({
                    NAME: "hex",
                    VAL: "F2F2F2"
                  })]);
}

export {
  add ,
  
}
/* CssJs Not a pure module */
