// Generated by ReScript, PLEASE EDIT WITH CARE


var Colors_primary = {
  NAME: "hex",
  VAL: "DD1350"
};

var Colors_black = {
  NAME: "hex",
  VAL: "0E0E0E"
};

var Colors_white = {
  NAME: "hex",
  VAL: "FAFAFA"
};

var Colors = {
  primary: Colors_primary,
  black: Colors_black,
  white: Colors_white
};

var Spacing_xxsmall = {
  NAME: "rem",
  VAL: 0.5
};

var Spacing_xsmall = {
  NAME: "rem",
  VAL: 1.0
};

var Spacing_small = {
  NAME: "rem",
  VAL: 1.5
};

var Spacing_medium = {
  NAME: "rem",
  VAL: 2.0
};

var Spacing_large = {
  NAME: "rem",
  VAL: 2.5
};

var Spacing_xlarge = {
  NAME: "rem",
  VAL: 3.0
};

var Spacing = {
  xxsmall: Spacing_xxsmall,
  xsmall: Spacing_xsmall,
  small: Spacing_small,
  medium: Spacing_medium,
  large: Spacing_large,
  xlarge: Spacing_xlarge
};

var Sizes_xsmall = {
  NAME: "rem",
  VAL: 0.625
};

var Sizes_small = {
  NAME: "rem",
  VAL: 0.75
};

var Sizes_medium = {
  NAME: "rem",
  VAL: 1.0
};

var Sizes_large = {
  NAME: "rem",
  VAL: 1.125
};

var Sizes_xlarge = {
  NAME: "rem",
  VAL: 1.25
};

var Sizes_xxlarge = {
  NAME: "rem",
  VAL: 1.5
};

var Sizes = {
  xsmall: Sizes_xsmall,
  small: Sizes_small,
  medium: Sizes_medium,
  large: Sizes_large,
  xlarge: Sizes_xlarge,
  xxlarge: Sizes_xxlarge
};

var Font = {
  light: 300,
  normal: 400,
  bold: 600,
  Sizes: Sizes
};

export {
  Colors ,
  Spacing ,
  Font ,
  
}
/* No side effect */
