// Generated by ReScript, PLEASE EDIT WITH CARE


var Colors_primary = {
  NAME: "hex",
  VAL: "DD1350"
};

var Colors_black = {
  NAME: "hex",
  VAL: "0E0E0E"
};

var Colors_white = {
  NAME: "hex",
  VAL: "FAFAFA"
};

var Colors = {
  primary: Colors_primary,
  black: Colors_black,
  white: Colors_white
};

var Spacing_xsmall = {
  NAME: "rem",
  VAL: 0.625
};

var Spacing_small = {
  NAME: "rem",
  VAL: 0.75
};

var Spacing_medium = {
  NAME: "rem",
  VAL: 1.0
};

var Spacing_large = {
  NAME: "rem",
  VAL: 1.125
};

var Spacing_xlarge = {
  NAME: "rem",
  VAL: 1.25
};

var Spacing = {
  xsmall: Spacing_xsmall,
  small: Spacing_small,
  medium: Spacing_medium,
  large: Spacing_large,
  xlarge: Spacing_xlarge
};

export {
  Colors ,
  Spacing ,
  
}
/* No side effect */
