// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.js";
import * as Theme from "../../styles/Theme.js";
import * as React from "react";

var wrapper = CssJs.style([
      CssJs.display("flex"),
      CssJs.flexDirection("column"),
      CssJs.width({
            NAME: "rem",
            VAL: 30
          })
    ]);

var title = CssJs.style([
      CssJs.cursor("pointer"),
      CssJs.color(Theme.Colors.primary),
      CssJs.fontWeight("bold"),
      CssJs.fontSize(Theme.Font.Sizes.xlarge)
    ]);

var description = CssJs.style([
      CssJs.marginTop(Theme.Spacing.xxsmall),
      CssJs.fontSize(Theme.Font.Sizes.medium)
    ]);

var texts = CssJs.style([CssJs.marginTop(Theme.Spacing.xsmall)]);

var img = CssJs.style([
      CssJs.width({
            NAME: "percent",
            VAL: 100.0
          }),
      CssJs.height({
            NAME: "percent",
            VAL: 100.0
          }),
      CssJs.objectFit("cover"),
      CssJs.borderRadius({
            NAME: "rem",
            VAL: 0.4
          })
    ]);

var Styles = {
  wrapper: wrapper,
  title: title,
  description: description,
  texts: texts,
  img: img
};

function PostCard(Props) {
  var title$1 = Props.title;
  var description$1 = Props.description;
  var img$1 = Props.img;
  return React.createElement("section", {
              className: wrapper
            }, React.createElement("img", {
                  className: img,
                  src: img$1
                }), React.createElement("div", {
                  className: texts
                }, React.createElement("h2", {
                      className: title
                    }, title$1), React.createElement("p", {
                      className: description
                    }, description$1)));
}

var make = PostCard;

export {
  Styles ,
  make ,
  
}
/* wrapper Not a pure module */
