// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.js";
import * as Theme from "../../styles/Theme.js";
import * as React from "react";
import * as PostCard from "../PostCard/PostCard.js";
import * as Separator from "../Separator/Separator.js";

var wrapper = CssJs.style([CssJs.marginTop(Theme.Spacing.xlarge)]);

var postsWrapper = CssJs.style([
      CssJs.display("flex"),
      CssJs.alignItems("center"),
      CssJs.justifyContent("spaceBetween"),
      CssJs.marginTop(Theme.Spacing.small)
    ]);

var Styles = {
  wrapper: wrapper,
  postsWrapper: postsWrapper
};

function PostsSection(Props) {
  var firstPost = Props.firstPost;
  var secondPost = Props.secondPost;
  return React.createElement("section", {
              className: wrapper
            }, React.createElement(Separator.make, {
                  children: "Últimos posts"
                }), React.createElement("div", {
                  className: postsWrapper
                }, React.createElement(PostCard.make, {
                      title: firstPost.title,
                      description: firstPost.description,
                      img: firstPost.img
                    }), React.createElement(PostCard.make, {
                      title: secondPost.title,
                      description: secondPost.description,
                      img: secondPost.img
                    })));
}

var make = PostsSection;

export {
  Styles ,
  make ,
  
}
/* wrapper Not a pure module */
