// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.js";
import * as Theme from "../../styles/Theme.js";
import * as React from "react";

var img = CssJs.style([
      CssJs.width({
            NAME: "rem",
            VAL: 4
          }),
      CssJs.height({
            NAME: "rem",
            VAL: 4
          })
    ]);

var wrapper = CssJs.style([
      CssJs.display("flex"),
      CssJs.flexDirection("column")
    ]);

var titleHover = CssJs.hover([CssJs.cursor("pointer")]);

var title = CssJs.style([
      CssJs.fontWeight("bold"),
      CssJs.fontSize(Theme.Font.Sizes.large),
      titleHover,
      CssJs.width({
            NAME: "percent",
            VAL: 100
          })
    ]);

var Styles = {
  img: img,
  wrapper: wrapper,
  title: title
};

function Icon(Props) {
  var title$1 = Props.title;
  var imgAltOpt = Props.imgAlt;
  var img$1 = Props.img;
  var imgAlt = imgAltOpt !== undefined ? imgAltOpt : "";
  return React.createElement("div", {
              className: wrapper
            }, React.createElement("img", {
                  className: img,
                  alt: imgAlt,
                  src: img$1
                }), React.createElement("h4", {
                  className: title
                }, title$1));
}

var make = Icon;

export {
  Styles ,
  make ,
  
}
/* img Not a pure module */
