// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.js";
import * as Theme from "../../styles/Theme.js";
import * as React from "react";

var img = CssJs.style([
      CssJs.width({
            NAME: "rem",
            VAL: 4
          }),
      CssJs.height({
            NAME: "rem",
            VAL: 4
          })
    ]);

var wrapper = CssJs.style([
      CssJs.display("flex"),
      CssJs.flexDirection("column"),
      CssJs.alignItems("center"),
      CssJs.justifyContent("center")
    ]);

var titleHover = CssJs.hover([CssJs.cursor("pointer")]);

var title = CssJs.style([
      CssJs.fontWeight("bold"),
      CssJs.fontSize(Theme.Font.Sizes.large),
      titleHover,
      CssJs.width({
            NAME: "percent",
            VAL: 100
          }),
      CssJs.textAlign("center")
    ]);

var linkVisited = CssJs.visited([CssJs.color(Theme.Colors.black)]);

var link = CssJs.style([
      CssJs.textDecoration("none"),
      CssJs.color(Theme.Colors.black),
      linkVisited
    ]);

var Styles = {
  img: img,
  wrapper: wrapper,
  title: title,
  link: link
};

function Icon(Props) {
  var title$1 = Props.title;
  var imgAltOpt = Props.imgAlt;
  var img$1 = Props.img;
  var hrefOpt = Props.href;
  var imgAlt = imgAltOpt !== undefined ? imgAltOpt : "";
  var href = hrefOpt !== undefined ? hrefOpt : "#";
  return React.createElement("div", {
              className: wrapper
            }, React.createElement("img", {
                  className: img,
                  alt: imgAlt,
                  src: img$1
                }), React.createElement("h4", {
                  className: title
                }, React.createElement("a", {
                      className: link,
                      href: href,
                      rel: "noopener noreferrer",
                      target: "_blank"
                    }, title$1)));
}

var make = Icon;

export {
  Styles ,
  make ,
  
}
/* img Not a pure module */
