// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Logo from "../Logo/Logo.js";
import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as Theme from "../../styles/Theme.js";
import * as React from "react";
import * as Button from "../Button/Button.js";

var wrapper = CssJs.style([
      CssJs.display("flex"),
      CssJs.justifyContent("spaceBetween"),
      CssJs.alignItems("center"),
      CssJs.height({
            NAME: "rem",
            VAL: 4
          }),
      CssJs.margin2(Theme.Spacing.medium, Theme.Spacing.large)
    ]);

var leftSide = CssJs.style([
      CssJs.width({
            NAME: "rem",
            VAL: 4
          }),
      CssJs.height({
            NAME: "rem",
            VAL: 4
          })
    ]);

var rightSide = CssJs.style([
      CssJs.display("flex"),
      CssJs.alignItems("center"),
      CssJs.marginRight(Theme.Spacing.medium)
    ]);

var navItemHover = CssJs.hover([
      CssJs.textDecoration("underline"),
      CssJs.textDecorationColor(Theme.Colors.primary)
    ]);

var navItem = CssJs.style([
      CssJs.marginLeft(Theme.Spacing.xsmall),
      CssJs.color(Theme.Colors.black),
      CssJs.textDecoration("none"),
      CssJs.fontWeight("semiBold"),
      navItemHover
    ]);

var Styles = {
  wrapper: wrapper,
  leftSide: leftSide,
  rightSide: rightSide,
  navItemHover: navItemHover,
  navItem: navItem
};

function Navbar(Props) {
  return React.createElement("nav", {
              className: wrapper
            }, React.createElement("div", {
                  className: rightSide
                }, React.createElement(Logo.make, {
                      color: "Black"
                    })), React.createElement("div", {
                  className: rightSide
                }, React.createElement("a", {
                      className: navItem,
                      href: ""
                    }, "Inicío"), React.createElement("a", {
                      className: navItem,
                      href: ""
                    }, "Faça parte"), React.createElement("a", {
                      className: navItem,
                      href: ""
                    }, "Quero aprender"), React.createElement(Button.make, {
                      children: "Blog",
                      size: "Small",
                      className: navItem
                    })));
}

var make = Navbar;

export {
  Styles ,
  make ,
  
}
/* wrapper Not a pure module */
