// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as PostCard from "./components/PostCard/PostCard.js";
import * as MainLayout from "./layouts/MainLayout.js";
import * as GlobalStyles from "./styles/GlobalStyles.js";

GlobalStyles.add(undefined);

function $$default(param) {
  return React.createElement(MainLayout.make, {
              children: React.createElement(PostCard.make, {
                    title: "Introdução ao Rescript e React",
                    description: "Primeira parte do artigo sobre Rescript e React",
                    img: "/static/post-placeholder.png"
                  })
            });
}

export {
  $$default ,
  $$default as default,
  
}
/*  Not a pure module */
