// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MainLayout from "./layouts/MainLayout.js";
import * as GlobalStyles from "./styles/GlobalStyles.js";

GlobalStyles.add(undefined);

function $$default(param) {
  return React.createElement(MainLayout.make, {
              children: React.createElement("div", undefined, "content")
            });
}

export {
  $$default ,
  $$default as default,
  
}
/*  Not a pure module */
