// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MainLayout from "./layouts/MainLayout.js";

function $$default(param) {
  return React.createElement(MainLayout.make, {
              children: "Hello there"
            });
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
