// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.js";
import * as Theme from "../../styles/Theme.js";
import * as React from "react";
import * as Button from "../Button/Button.js";

var wrapper = CssJs.style([
      CssJs.display("flex"),
      CssJs.alignItems("center"),
      CssJs.justifyContent("spaceBetween"),
      CssJs.width({
            NAME: "rem",
            VAL: 64
          })
    ]);

var title = CssJs.style([
      CssJs.fontSize(Theme.Font.Sizes.huge),
      CssJs.marginBottom(Theme.Spacing.small),
      CssJs.fontWeight("bold")
    ]);

var banner = CssJs.style([
      CssJs.display("flex"),
      CssJs.flexDirection("column")
    ]);

var Styles = {
  wrapper: wrapper,
  title: title,
  banner: banner
};

function IntroSection(Props) {
  return React.createElement("section", {
              className: wrapper
            }, React.createElement("div", {
                  className: banner
                }, React.createElement("h2", {
                      className: title
                    }, "Comunidade ReasonML & Rescript Brasil"), React.createElement(Button.make, {
                      children: "Faça parte",
                      size: "Medium"
                    })), React.createElement("img", {
                  src: "static/building.svg"
                }));
}

var make = IntroSection;

export {
  Styles ,
  make ,
  
}
/* wrapper Not a pure module */
