// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as React from "react";

var wrapper = CssJs.style([
      CssJs.display("flex"),
      CssJs.alignItems("center"),
      CssJs.justifyContent("center")
    ]);

function MainLayout(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: wrapper
            }, React.createElement("main", undefined, children));
}

var make = MainLayout;

export {
  make ,
  
}
/* wrapper Not a pure module */
